[project]
selected = "g5k"

[params]
nb_nodes = 2

[g5k.options]
kernel-params = "systemd.unified_cgroup_hierarchy=0"

# [g5k.build.nur.repos.kapack.oar]
# src = "/home/afaure/code/oar3"

# [g5k.build.nur.repos.kapack.oar3]
# src = "/home/afaure/code/oar3"

[laptop.options]
nix-flags = "--impure" # --override-input kapack path:/home/adfaure/Sandbox/nxc-melissa/nur-kapack"

# [laptop.overrides.nur.kapack]
# ear = { src = "/home/auguste/dev/ear" }

[dev-alex.options]
nix-flags = "--impure --override-input kapack path:/home/alex/dev/nur-kapack-regale/regale-221"

# [dev-alex.build.nur.repos.kapack]
# oar = { src = "/home/alex/dev/oar-versions/oar3" }
