[project]

    
[g5k-dev.options]
nix-flags = "--impure"    
          
[g5k-dev.build.nur.repos.kapack]
ear = { src = "/home/orichard/ear" }

[dev.options]
nix-flags = "--impure --override-input kapack path:/home/auguste/dev/nur-kapack/regale"

[dev.build.nur.repos.kapack]
ear = { src = "/home/auguste/dev/ear" }
