[project]
selected = "dev"

[params]
nb_nodes = 2

[g5k.options]
nix-flags = "--impure --override-input kapack path:/home/afaure/regale-nixos-compose/nur-kapack"

[laptop.options]
nix-flags = "--impure --override-input kapack path:/home/adfaure/Sandbox/nxc-melissa/nur-kapack"
[dev.options]
nix-flags = "--impure"
nix-flags = "--impure --override-input kapack path:/home/auguste/dev/nur-kapack/regale"
        
[dev.build.nur.repos.kapack]
melissa.src = "/home/auguste/dev/melissa-combined"
melissa-launcher.src = "/home/auguste/dev/melissa-combined" 
melissa-heat-pde.src = "/home/auguste/dev/melissa-combined"




