[project]

[params]
nb_nodes = 2

[g5k.options]
nix-flags = "--impure --override-input kapack path:/home/afaure/code/nur-kapack"
kernel-params = "systemd.unified_cgroup_hierarchy=0"

[laptop.options]
nix-flags = "--impure" # --override-input kapack path:/home/adfaure/Sandbox/nxc-melissa/nur-kapack"

[dev-alex.options]
nix-flags = "--impure --override-input kapack path:/home/alex/dev/nur-kapack-regale/regale-221"
