[project]

[g5k-dev.options]
nix-flags = "--impure"    
          
[g5k.build.nur.repos.kapack.ear]
src = "/home/orichard/ear"

[laptop.options]
nix-flags = "--impure --override-input kapack path:/home/auguste/dev/nur-kapack/regale"

[laptop.build.nur.repos.kapack.ear]
src = "/home/auguste/dev/ear"
