[project]
selected = "dev-alex"
    
[options.build.nur.repos.kapack.ear.attrs]    
meta.broken = false

[g5k-dev.options]
nix-flags = "--impure --override-input kapack path:/home/orichard/nur-kapack/regale"    
          
#[g5k.build.nur.repos.kapack.ear]
#src = "/home/orichard/ear"

[dev.options]
nix-flags = "--impure --override-input kapack path:/home/auguste/dev/nur-kapack/regale"

[dev.build.nur.repos.kapack.ear]
src = "/home/auguste/dev/ear"

[dev-alex.options]
nix-flags = "--impure --override-input kapack path:/home/alex/dev/nur-kappack-regale/regale-2211"

[dev-alex.build.nur.repos.kapack]
oar = { src = "/home/alex/dev/oar-versions/oar3" }
