[project]
selected = "g5k"

[params]
nb_nodes = 3

[g5k.options]
nix-flags = "--impure --override-input kapack path:/home/afaure/code/nur-kapack"

[laptop.options]
nix-flags = "--impure" # --override-input kapack path:/home/adfaure/code/nur-kapack"

# [laptop.overrides.nur.kapack]
# ear = { src = "/home/auguste/dev/ear" }

[dev-alex.options]
nix-flags = "--impure --override-input kapack path:/home/alex/dev/nur-kapack-regale/regale-2211"

# [dev-alex.build.nur.repos.kapack]
# oar = { src = "/home/alex/dev/oar-versions/oar3" }
