[project]
selected = "laptop"

[params]
nb_nodes = 3

[g5k.options]
nix-flags = "--impure --override-input kapack path:/home/afaure/regale-nixos-compose/nur-kapack"

[laptop.options]
nix-flags = "--impure --override-input kapack path:/home/adfaure/Sandbox/nxc-melissa/nur-kapack"

# [laptop.overrides.nur.kapack]
# ear = { src = "/home/auguste/dev/ear" }
