[project]
selected = "laptop"

    
[g5k.options]
nix-flags = "--impure"    
          

[laptop.options]
nix-flags = "--impure --override-input kapack path:/home/auguste/dev/nur-kapack/regale"

[laptop.overrides.nur.kapack]
ear = { src = "/home/auguste/dev/ear" }
