[project]
selected = "g5k"

[g5k.options]
nix-flags = "--impure --override-input kapack path:/home/afaure/regale-nixos-compose/nur-kapack"

[laptop.options]
nix-flags = "--impure --override-input kapack path:/home/auguste/dev/nur-kapack/regale"

[laptop.overrides.nur.kapack]
ear = { src = "/home/auguste/dev/ear" }
